[build]
  publish = "frontend"

[[redirects]]
  from = "/benchmark"
  to = "/benchmark.html"
  status = 200

[[redirects]]
  from = "/appendix"
  to = "/appendix.html"
  status = 200

[[redirects]]
  from = "/whitepaper"
  to = "/whitepaper.html"
  status = 200

[[redirects]]
  from = "/payloads"
  to = "/payloads/"
  status = 200
